services:
  server:
    image: itzg/minecraft-server:java21-alpine
    pull_policy: daily
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      MOTD: "§e§l§oPokémon §8§lBlack §r§f& §f§lWhite §r§7"
      SPAWN_PROTECTION: 0

      TYPE: MODRINTH
      MODRINTH_MODPACK: /server.mrpack
      MEMORY: 12G

      ENABLE_RCON: "true"
      ENFORCE_SECURE_PROFILE: "false"
      RCON_PASSWORD: "${RCON_PASSWORD:-minecraft}"
      RCON_PORT: 25575
      ALLOW_FLIGHT: "true"

    volumes:
      - ./data:/data
      - ./server.mrpack:/server.mrpack:ro
    ports:
      - "25565:25565/tcp"
      - "24454:24454/udp"

  backup:
    image: cobblemon-bw-backup:latest
    restart: on-failure
    build: 
      context: ./backup
    depends_on:
      - server
    environment:
      # RCON
      RCON_HOST: server:25575
      RCON_PORT: 25575
      RCON_PASSWORD: "${RCON_PASSWORD:-minecraft}"

      SSH_USER: albercl
      SSH_HOST: nas.albercl.dev
      SSH_PATH: ~/backups/cobblemon-bw

    volumes:
      - ./data:/data:ro
      - ~/.ssh/id_ed25519:/root/.ssh/id:ro
  
